apiVersion: v1
kind: ConfigMap
metadata:
  name: dovecot-conf
data:
  dovecot.conf: |
    # 2.3.15 (0503334ab1): /etc/dovecot/dovecot.conf
    # Pigeonhole version 0.5.15 (e6a84e31)
    # OS: Linux 5.14.18-300.fc35.x86_64 x86_64  btrfs
    # Hostname: fee040f9de2e
    first_valid_uid = 100
    log_path = /dev/stdout
    mail_debug = yes
    auth_debug = yes 
    mail_gid = 102
    mail_location = maildir:/var/lib/vmail/%d/%u/
    mail_uid = 101
    managesieve_notify_capability = mailto
    managesieve_sieve_capability = fileinto reject envelope encoded-character vacation subaddress comparator-i;ascii-numeric relational regex imap4flags copy include variables body enotify environment mailbox date index ihave duplicate mime foreverypart extracttext
    mbox_write_locks = fcntl
    namespace inbox {
      inbox = yes
      location =
      mailbox Drafts {
        special_use = \Drafts
      }
      mailbox Junk {
        special_use = \Junk
      }
      mailbox Sent {
        special_use = \Sent
      }
      mailbox "Sent Messages" {
        special_use = \Sent
      }
      mailbox Trash {
        special_use = \Trash
      }
      prefix =
    }
    passdb {
      args = /etc/dovecot/dovecot-ldap.conf.ext
      driver = ldap
    }
    plugin {
      sieve = file:~/sieve;active=~/.dovecot.sieve
    }
    ssl = required
    ssl_cert = </etc/dovecot/ssl/tls.crt
    ssl_key = </etc/dovecot/ssl/tls.key
    ssl_prefer_server_ciphers = yes
    userdb {
      args = /etc/dovecot/dovecot-ldap.conf.ext
      driver = ldap
    }
    service auth {
      inet_listener auth {
        port = 5000
      }
    }
    auth_mechanisms = plain login
  dovecot-ldap.conf.ext: |
    uris = {{ .Values.ldap.uri }}
    auth_bind = yes
    auth_bind_userdn = maildrop=%u,{{ .Values.ldap.base }}
    base = {{ .Values.ldap.base }}
    user_filter = (&(objectClass=postfixUser)(maildrop=%u))
