apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: dovecot
  labels:
    app: dovecot
spec:
  selector:
    matchLabels:
      app: dovecot
  podMetricsEndpoints:
  - port: metrics
