---
apiVersion: v1
kind: Service
metadata:
  name: dovecot
  labels:
    app: dovecot
spec:
  type: ClusterIP
  ports:
    - name: tcp-imap
      port: 143
      targetPort: imap
    - name: tcp-imaps
      port: 993
      targetPort: imaps
  selector:
    app: dovecot
