---
apiVersion: v1
kind: Service
metadata:
  name: dovecot-auth
  labels:
    app: dovecot
spec:
  type: ClusterIP
  ports:
    - name: auth
      port: 5000
      targetPort: auth
  selector:
    app: dovecot
