---
apiVersion: v1
kind: Service
metadata:
  name: dovecot
  labels:
    app: dovecot
  annotations:
     metallb.universe.tf/allow-shared-ip: ingress-ip
     external-dns.alpha.kubernetes.io/hostname: imap.{{ .Values.domain }}
spec:
  type: LoadBalancer
  ports:
    - name: tcp-imap
      port: 143
      targetPort: imap
    - name: tcp-imaps
      port: 993
      targetPort: imaps
  selector:
    app: dovecot
