apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: dovecot-ssl-cert
spec:
  secretName: dovecot-ssl-cert
  dnsNames:
    - imap.{{ .Values.domain }}
  issuerRef:
    group: cert-manager.io
    kind: ClusterIssuer
    name: acme-issuer

